config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  resources :users
  resources :roles
  resources :cars
  resources :addresses
  resources :clients
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root to: 'public#home'

  get 'about', to: 'public#about'

  resources :client do
    resources :cars
    resources :addresses
  end
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, Client, public: true

    return unless user.present?
    can :manage, :all
  end
end

app/models/address.rb
# frozen_string_literal: true

class Address < ApplicationRecord
  belongs_to :client

  validates :street, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :number, presence: true
  validates :client_id, presence: true
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/car.rb
# frozen_string_literal: true

class Car < ApplicationRecord
  belongs_to :client

  validates :licence_plate, presence: true
  validates :client_id, presence: true
end

app/models/client.rb
# frozen_string_literal: true

class Client < ApplicationRecord
  belongs_to :user
  has_many :addresses
  has_many :cars

  validates :name, presence: true
end

app/models/controller.rb
class Controller < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/role.rb
class Role < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :role
  has_many :clients
end

app/controllers/addresses_controller.rb
# frozen_string_literal: true

class AddressesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_address, only: %i[show edit update destroy]

  # GET /addresses or /addresses.json
  def index
    @addresses = @client.addresses
  end

  # GET /addresses/1/edit
  def edit; end

  # POST /addresses or /addresses.json
  def create
    @client = Client.find(params[:client_id])
    @address = @client.addresses.create(address_params)

    redirect_to user_client_path(@client.user_id, @client.id)
  end

  # PATCH/PUT /addresses/1 or /addresses/1.json
  def update
    respond_to do |format|
      if @address.update(address_params)
        format.html { redirect_to user_client_path(@client.user_id, @client.id), notice: 'Address was successfully updated.' }
        format.json { render :show, status: :ok, location: @address }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addresses/1 or /addresses/1.json
  def destroy
    @address.destroy

    
    redirect_to user_client_path(@client.user_id, @client.id)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_address
    @user = User.find(params[:user_id])
    @client = @user.clients.find(params[:client_id])
    @address = @client.addresses.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def address_params
    params.fetch(:address, {}).permit(:street, :city, :state, :number, :details, :client_id)
  end
end

app/controllers/cars_controller.rb
# frozen_string_literal: true

class CarsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_car, only: %i[show edit update destroy]

  # POST /cars or /cars.json
  def create
    @client = Client.find(params[:client_id])
    @car = @client.cars.create(car_params)

    redirect_to user_client_path(@client.user_id, @client.id)
  end

  # DELETE /addresses/1 or /addresses/1.json
  def destroy
    @car.destroy

    redirect_to user_client_path(@client.user_id, @client.id)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_car
    @user = User.find(current_user.id)
    @client = Client.find(params[:client_id])
    @car = @client.cars.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def car_params
    params.fetch(:car, {}).permit(:licence_plate, :client_id)
  end
end

app/controllers/public_controller.rb
# frozen_string_literal: true

class PublicController < ApplicationController
  def home
    
  end

  def about
  end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :set_role, only: %i[ show edit update destroy ]

  # GET /roles
  def index
    @roles = Role.all
  end

  # GET /roles/1
  def show
  end

  # GET /roles/new
  def new
    @role = Role.new
  end

  # GET /roles/1/edit
  def edit
  end

  # POST /roles
  def create
    @role = Role.new(role_params)

    if @role.save
      redirect_to @role, notice: "Role was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /roles/1
  def update
    if @role.update(role_params)
      redirect_to @role, notice: "Role was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /roles/1
  def destroy
    @role.destroy
    redirect_to roles_url, notice: "Role was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_role
      @role = Role.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def role_params
      params.require(:role).permit(:name, :description)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
    before_action :set_user, only: %i[show edit update destroy]
    
    def show
    end

    def create
        @user = User.new(user_params)
        if @user.save
            redirect_to @user, notice: 'User was successfully created.'
        else
            render :new
        end
    end
    

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_user
        @user = User.find(params[:id])
    end

    def user_params
        params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :role_id)
    end
end

app/helpers/addresses_helper.rb
# frozen_string_literal: true

module AddressesHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/cars_helper.rb
# frozen_string_literal: true

module CarsHelper
end

app/helpers/clients_helper.rb
# frozen_string_literal: true

module ClientsHelper
end

app/helpers/public_helper.rb
# frozen_string_literal: true

module PublicHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/addresses/_address.html.erb
<div id="<%= dom_id address %>" class="card m-2">
    <div class="card-body">
        <div>
            <%= address.street %> <%= address.number %>, <%= address.state %>, <%= address.city %>
        </div>
        <div><%= address.details %></div>
        <div class="form-actions">
            <%= button_to "Borrar", user_client_address_path(@client.user_id, @client.id, address.id), method: :delete, class:'btn btn-danger btn-block' %>
        </div>
    </div>
</div>

app/views/addresses/_form.html.erb
<%= form_with model: [@user, @user.clients.find(@client.id), @user.clients.find(@client.id).addresses.build ] do |form| %>
  <% if address.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(address.errors.count, "error") %> no permitieron guardar esta dirección:</h2>

      <ul>
        <% address.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-field">
      <%= form.label :street, "Calle" %>
      <%= form.text_field :street %>
  </div>
  <div class="form-field">
      <%= form.label :number, "Número" %>
      <%= form.text_field :number %>
  </div>
  <div class="form-field">
      <%= form.label :state, "Comuna" %>
      <%= form.text_field :state %>
  </div>
  <div class="form-field">
      <%= form.label :city, "Ciudad" %>
      <%= form.text_field :city %>
  </div>
  <div class="form-field">
      <%= form.label :details, "Detalles" %>
      <%= form.text_field :details %>
  </div>
  <div class="form-actions">
    <%= form.submit "Agregar", class:'btn btn-primary btn-block' %>
  </div>
<% end %>

app/views/addresses/edit.html.erb
<h1>Editing address</h1>

<%= render "form", address: @address %>

<br>

<div>
  <%= link_to "Show this address", @address %> |
  <%= link_to "Back to addresses", addresses_path %>
</div>

app/views/addresses/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Addresses</h1>

<div id="addresses">
  <% @addresses.each do |address| %>
    <%= render address %>
    <p>
      <%= link_to "Show this address", address %>
    </p>
  <% end %>
</div>

<%= link_to "New address", new_address_path %>

app/views/addresses/new.html.erb
<h1>New address</h1>

<%= render "form", address: @address %>

<br>

<div>
  <%= link_to "Back to addresses", addresses_path %>
</div>

app/views/addresses/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @address %>

<div>
  <%= link_to "Edit this address", edit_address_path(@address) %> |
  <%= link_to "Back to addresses", addresses_path %>

  <%= button_to "Destroy this address", @address, method: :delete %>
</div>