config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  resources :users
  resources :roles
  resources :cars
  resources :addresses
  resources :clients
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root to: 'public#home'

  get 'about', to: 'public#about'

  resources :client do
    resources :cars
    resources :addresses
  end
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, Client, public: true

    return unless user.present?
    can :manage, :all
  end
end

app/models/address.rb
# frozen_string_literal: true

class Address < ApplicationRecord
  belongs_to :client

  validates :street, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :number, presence: true
  validates :client_id, presence: true
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/car.rb
# frozen_string_literal: true

class Car < ApplicationRecord
  belongs_to :client

  validates :licence_plate, presence: true
  validates :client_id, presence: true
end

app/models/client.rb
# frozen_string_literal: true

class Client < ApplicationRecord
  belongs_to :user
  has_many :addresses
  has_many :cars

  validates :name, presence: true
end

app/models/controller.rb
class Controller < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/role.rb
class Role < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :role
  has_many :clients
end

app/controllers/cars_controller.rb
# frozen_string_literal: true

class CarsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_car, only: %i[show edit update destroy]

  # POST /cars or /cars.json
  def create
    @client = Client.find(params[:client_id])
    @car = @client.cars.create(car_params)

    redirect_to user_client_path(@client.user_id, @client.id)
  end

  # DELETE /addresses/1 or /addresses/1.json
  def destroy
    @car.destroy

    redirect_to user_client_path(@client.user_id, @client.id)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_car
    @user = User.find(current_user.id)
    @client = Client.find(params[:client_id])
    @car = @client.cars.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def car_params
    params.fetch(:car, {}).permit(:licence_plate, :client_id)
  end
end

app/controllers/clients_controller.rb
# frozen_string_literal: true

class ClientsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_client, only: %i[show edit update destroy share]

  # GET /clients or /clients.json
  def index
    @user = User.find(params[:user_id])
    @clients = @user.clients.all
    @shared_clients = Client.where('shared = ? and user_id != ?', true, @user.id)
  end

  # GET /clients/1 or /clients/1.json
  def show
    @user = User.find(params[:user_id])
  end

  # GET /clients/new
  def new
    @user = User.find(params[:user_id])
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
    @user = User.find(params[:user_id])
  end

  # POST /clients or /clients.json
  def create
    @user = User.find(params[:user_id])
    @client = @user.clients.create(client_params)

    redirect_to user_clients_url(@user)
  end

  def share
    @user = User.find(params[:user_id])
    @client = Client.find(params[:id])
    if (@user.id == @client.user_id) then
      if @client.shared then
        @client.update(shared: false)
      else
        @client.update(shared: true)
      end
    end
  end

  # PATCH/PUT /clients/1 or /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to client_url(@client), notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1 or /clients/1.json
  def destroy
    @client.destroy

    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_client
    @client = Client.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def client_params
    params.fetch(:client, {}).permit(:name, :phone)
  end
end

app/controllers/public_controller.rb
# frozen_string_literal: true

class PublicController < ApplicationController
  def home
    
  end

  def about
  end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :set_role, only: %i[ show edit update destroy ]

  # GET /roles
  def index
    @roles = Role.all
  end

  # GET /roles/1
  def show
  end

  # GET /roles/new
  def new
    @role = Role.new
  end

  # GET /roles/1/edit
  def edit
  end

  # POST /roles
  def create
    @role = Role.new(role_params)

    if @role.save
      redirect_to @role, notice: "Role was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /roles/1
  def update
    if @role.update(role_params)
      redirect_to @role, notice: "Role was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /roles/1
  def destroy
    @role.destroy
    redirect_to roles_url, notice: "Role was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_role
      @role = Role.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def role_params
      params.require(:role).permit(:name, :description)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email].downcase)
    if user && user.authenticate(params[:email], params[:password])
      sign_in user
      redirect_to root_url, notice: 'Logged in!'
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to login_path, notice: 'Logged out!'
  end

  def sign_in(user)
    session[:user_id] = user.id
  end

  def sign_out
    session[:user_id] = nil
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
    before_action :set_user, only: %i[show edit update destroy]
    
    def show
    end

    def create
        @user = User.new(user_params)
        if @user.save
            redirect_to @user, notice: 'User was successfully created.'
        else
            render :new
        end
    end
    

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_user
        @user = User.find(params[:id])
    end

    def user_params
        params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :role_id)
    end
end

app/helpers/addresses_helper.rb
# frozen_string_literal: true

module AddressesHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/cars_helper.rb
# frozen_string_literal: true

module CarsHelper
end

app/helpers/clients_helper.rb
# frozen_string_literal: true

module ClientsHelper
end

app/helpers/public_helper.rb
# frozen_string_literal: true

module PublicHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cars/_car.html.erb
<div id="<%= dom_id car %>" class="card m-2">
    <div class="card-body">
        <strong><%= car.licence_plate %></strong>
        <div class="form-actions">
            <%= button_to "Borrar", user_client_car_path(@client.user_id, @client.id, car.id), method: :delete, class:"btn btn-danger"%>
        </div>
    </div>
</div>

app/views/cars/_form.html.erb
<%= form_with model: [@user, @user.clients.find(@client.id), @user.clients.find(@client.id).cars.build] do |form| %>
  <% if car.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(car.errors.count, "error") %> no permitieron guardar el auto:</h2>

      <ul>
        <% car.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-field">
      <%= form.label :licence_plate, "Patente" %>
      <%= form.text_field :licence_plate %>
  </div>
  
  <div class="form-actions">
      <%= form.submit "Agregar auto", class:'btn btn-primary btn-block'%>
  </div>
<% end %>

app/views/cars/edit.html.erb
<h1>Editing car</h1>

<%= render "form", car: @car %>

<br>

<div>
  <%= link_to "Show this car", @car %> |
  <%= link_to "Back to cars", cars_path %>
</div>

app/views/cars/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @car %>

<div>
  <%= link_to "Edit this car", edit_car_path(@car) %> |
  <%= link_to "Back to cars", cars_path %>

  <%= button_to "Destroy this car", @car, method: :delete %>
</div>

app/views/clients/_client.html.erb
<div id="<%= dom_id client %>" class="card m-3">
    <div class="card-header">
        <h2><%= client.name %> <%= client.phone %> <%= if (client.user_id == @user.id && client.shared) then 'Compartido' end %></h2>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col">
                <h4>Autos</h4>
                <% if client.cars.count > 0 %>
                    <% client.cars.each do |car| %>
                        <div class="card m-1">
                            <div class="card-body">
                                <%= car.licence_plate %>
                            </div>
                        </div>
                    <% end %>
                <% else %>
                    <p>No hay autos registrados</p>
                <% end %>
            </div>
            <div class="col">
                <h4>Direcciones</h4>
                <% if client.addresses.count > 0 %>
                    <% client.addresses.each_with_index do |address, index| %>
                        <div class="card m-1">
                            <div class="card-body">
                                #<%=index+1 %> <%= address.street %> <%= address.number %>, <%= address.state %>
                            </div>
                        </div>
                    <% end %>
                <% else %>
                    <p>No hay direcciones registradas</p>
                <% end %>
            </div>
        </div>
    </div>
    <div class="card-footer">
        <div class="form-actions">
            <%= button_to "Ver", user_client_path(@user.id, client), method: :get, class:"btn btn-primary btn-block" %>
        </div>
    </div>
</div>

app/views/clients/_form.html.erb
<%= form_with model: [ @user, @user.clients.build ] do |form| %>
  
  <div class="form-field">
      <%= form.label :name, "Nombre" %>
      <%= form.text_field :name %>
  </div>
  
  <div class="form-field">
      <%= form.label :phone, "Teléfono" %>
      <%= form.text_field :phone %>
  </div>
  
  <div class="form-actions">
      <%= form.submit "Guardar", class:'btn btn-primary btn-block'%>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing client</h1>

<%= render "form", client: @client %>

<br>

app/views/clients/index.html.erb
<h1 class="m-3">Clientes <%= button_to "Agregar", new_user_client_path(@user.id), method: :get, class:'btn btn-primary btn-block' %></h1>

<div id="clients">
    <% @clients.each do |client| %>
      <%= render client %>
    <% end %>

    <% if (@shared_clients.length > 0) %>
      <h1>Compartidos</h1>
      <% @shared_clients.each do |client| %>
        <%= render client %>
      <% end %>
    <% end %>
</div>

app/views/clients/new.html.erb
<h1>Crear cliente</h1>

<%= render "form", client: @client %>

app/views/clients/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="card">
    <div class="card-header">
        <h2><%= @client.name %> [+56 <%= @client.phone %>]</h2>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col">
                <h4>Autos</h4>
                <% if @client.cars.count > 0 %>
                    <% @client.cars.each do |car| %>
                        <%= render car %>
                    <% end %>
                <% else %>
                    <p>No hay autos registrados</p>
                <% end %>
            </div>
            <div class="col">
                <h4>Direcciones</h4>
                <% if @client.addresses.count > 0 %>
                    <% @client.addresses.each_with_index do |address, index| %>
                        <%= render address %>
                    <% end %>
                <% else %>
                    <p>No hay direcciones registradas</p>
                <% end %>
            </div>
        </div>
    </div>
    <div class="card-footer">
        <div class="row">
            <div class="col">
                <div class="form">
                    <%= render "cars/form", car: @client.cars.build %>
                </div>
            </div>
            
            <div class="col">
                <div class="form">
                    <%= render "addresses/form", address: @client.addresses.build %>
                </div>
            </div>
        </div>
    </div>
</div>


<div>
  <%= link_to "Edit this client", edit_user_client_path(@user.id, @client) %> 
</div>

app/views/roles/_form.html.erb
<%= form_with(model: role) do |form| %>
  <% if role.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(role.errors.count, "error") %> prohibited this role from being saved:</h2>

      <ul>
        <% role.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/roles/_role.html.erb
<div id="<%= dom_id role %>">
  <p>
    <strong>Name:</strong>
    <%= role.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= role.description %>
  </p>

</div>

app/views/roles/edit.html.erb
<h1>Editing role</h1>

<%= render "form", role: @role %>

<br>

<div>
  <%= link_to "Show this role", @role %> |
  <%= link_to "Back to roles", roles_path %>
</div>

app/views/roles/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Roles</h1>

<div id="roles">
  <% @roles.each do |role| %>
    <%= render role %>
    <p>
      <%= link_to "Show this role", role %>
    </p>
  <% end %>
</div>

<%= link_to "New role", new_role_path %>

app/views/roles/new.html.erb
<h1>New role</h1>

<%= render "form", role: @role %>

<br>

<div>
  <%= link_to "Back to roles", roles_path %>
</div>

app/views/roles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @role %>

<div>
  <%= link_to "Edit this role", edit_role_path(@role) %> |
  <%= link_to "Back to roles", roles_path %>

  <%= button_to "Destroy this role", @role, method: :delete %>
</div>