config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  resources :users
  resources :roles
  resources :cars
  resources :addresses
  resources :clients
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root to: 'public#home'

  get 'about', to: 'public#about'

  resources :client do
    resources :cars
    resources :addresses
  end
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, Client, public: true

    return unless user.present?
    can :manage, :all
  end
end

app/models/address.rb
# frozen_string_literal: true

class Address < ApplicationRecord
  belongs_to :client

  validates :street, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :number, presence: true
  validates :client_id, presence: true
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/car.rb
# frozen_string_literal: true

class Car < ApplicationRecord
  belongs_to :client

  validates :licence_plate, presence: true
  validates :client_id, presence: true
end

app/models/client.rb
# frozen_string_literal: true

class Client < ApplicationRecord
  belongs_to :user
  has_many :addresses
  has_many :cars

  validates :name, presence: true
end

app/models/controller.rb
class Controller < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/role.rb
class Role < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :role
  has_many :clients
end

app/controllers/cars_controller.rb
# frozen_string_literal: true

class CarsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_car, only: %i[show edit update destroy]

  # POST /cars or /cars.json
  def create
    @client = Client.find(params[:client_id])
    @car = @client.cars.create(car_params)

    redirect_to user_client_path(@client.user_id, @client.id)
  end

  # DELETE /addresses/1 or /addresses/1.json
  def destroy
    @car.destroy

    redirect_to user_client_path(@client.user_id, @client.id)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_car
    @user = User.find(current_user.id)
    @client = Client.find(params[:client_id])
    @car = @client.cars.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def car_params
    params.fetch(:car, {}).permit(:licence_plate, :client_id)
  end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :set_role, only: %i[ show edit update destroy ]

  # GET /roles
  def index
    @roles = Role.all
  end

  # GET /roles/1
  def show
  end

  # GET /roles/new
  def new
    @role = Role.new
  end

  # GET /roles/1/edit
  def edit
  end

  # POST /roles
  def create
    @role = Role.new(role_params)

    if @role.save
      redirect_to @role, notice: "Role was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /roles/1
  def update
    if @role.update(role_params)
      redirect_to @role, notice: "Role was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /roles/1
  def destroy
    @role.destroy
    redirect_to roles_url, notice: "Role was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_role
      @role = Role.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def role_params
      params.require(:role).permit(:name, :description)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
    before_action :set_user, only: %i[show edit update destroy]
    
    def show
    end

    def create
        @user = User.new(user_params)
        if @user.save
            redirect_to @user, notice: 'User was successfully created.'
        else
            render :new
        end
    end
    

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_user
        @user = User.find(params[:id])
    end

    def user_params
        params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :role_id)
    end
end

app/helpers/addresses_helper.rb
# frozen_string_literal: true

module AddressesHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/cars_helper.rb
# frozen_string_literal: true

module CarsHelper
end

app/helpers/clients_helper.rb
# frozen_string_literal: true

module ClientsHelper
end

app/helpers/public_helper.rb
# frozen_string_literal: true

module PublicHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_alerts.html.erb
<% if alert %>
    <p class="alert alert-danger m-3"><%= alert %></p>
<% end %>
<% if notice %> 
    <p class="alert alert-success m-3"><%= notice %></p>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <%= link_to "RevTec", root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if current_user %>
          <li class="nav-item">
            <%= link_to "Mis clientes", user_clients_url(current_user.id), class:"nav-link"%>
          </li>
        <% end %>
        <li class="nav-item">
          <a class="nav-link" href="/about">About</a>
        </li>
        
      </ul>
      <ul class="navbar-nav">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <i class="bi bi-menu-button-wide"></i> <% if current_user %><%= current_user.first_name %><% else %> Sesión<% end %>
          </a>
          <ul class="dropdown-menu dropdown-menu-lg-end" aria-labelledby="navbarDropdown">
          <% if current_user %>
            <li><h6 class="dropdown-header">Acciones</h6></li>
            <li>
                <%= link_to " Crear cliente", new_user_client_path(current_user.id), class:"dropdown-item bi bi-person-plus" %>
            </li>
            <li>
                <%= link_to " Agendar revisión", root_path, class:"dropdown-item bi bi-calendar-plus" %>
            </li>
            <li>
                <hr class="dropdown-divider">
            </li>
          <% end %>
            <li><h6 class="dropdown-header">Sesión</h6></li>
            <% if !current_user %>
              <li>
                <%= link_to " Crear cuenta", new_user_registration_path, class:"dropdown-item bi bi-person-plus" %>
              </li>
              <li>
                <%= link_to " Iniciar sesión", new_user_session_path, class:"dropdown-item bi bi-box-arrow-in-right" %>
              </li>
            <% else %>
              <li>
                <%= link_to " Perfil", user_path(current_user.id), class:"dropdown-item bi bi-person" %>
              </li>
              <li>
                <%= button_to " Cerrar sesión", destroy_user_session_path, method: :delete, class:"dropdown-item bi bi-box-arrow-right" %>
              </li>
            <% end %>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Revtec</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.2/font/bootstrap-icons.css" integrity="sha384-eoTu3+HydHRBIjnCVwsFyCpUDZHZSFKEJD0mc3ZqSBSb6YhZzRHeiomAUWCstIWo" crossorigin="anonymous">
    
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <%= render "layouts/navbar" %>
      <%= render "layouts/alerts" %>
    </header>
    <div class="container">
        <main>
          <%= yield %>
        </main>
    </div>
  </body>
</html>